FROM debian:buster

MAINTAINER NAME   : JO YUN HO \
		   E-MAIL : yujo@student.42seoul.kr \
		   GITHUB : https://gitgub.com/YUJO42 \
		   BLOG   : https://velog.io/@yujo

# update debian
RUN apt-get update && apt-get -y upgrade

# intsall basic tools and NginX
RUN apt-get install -y git vim curl wget nginx

# install PHP
RUN apt-get install -y php php-fpm php-mysql

# install

