# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    config.yaml                                        :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: yujo <yujo@student.42seoul.kr>             +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/09/23 13:20:05 by yujo              #+#    #+#              #
#    Updated: 2020/09/23 15:58:59 by yujo             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

